version: '3.8'

services:

  # PHP-FPM Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    
    container_name: ${APP_NAME}-php
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ./:/var/www

    depends_on:
      - mysql

    networks:
      - app-network

  # NGINX Service
  webserver:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    tty: true
    
    ports:
      - "8000:80"
      - "8001:443"

    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

    depends_on:
      - app

    networks:
      - app-network
  
  # Redis service
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:3
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"

    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}-mysql
    restart: unless-stopped
    
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    
    ports:
      - '${DB_PORT}:3306'

    expose:
      - '3306'
    
    volumes: 
      - dbdata:/var/lib/mysql

    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge